### ISSUE TITLE
Tokens builder

### ISSUE THREAD

**Issue by equinusocio** [wonderflow-bv/tokens#1]
## What

We need to define the tokens scheme used by other packages. Design tokens are the platform-agnostic vocabulary for our interfaces.

## How

Such `core` style should include `raw tokens` and platform-specific tokens

### Output

The tokens output must be:

 - A `json` that includes all the tokens formatted and converted
 - A `css` file with the list of all the tokens as custom properties (inside the `:root` selector)
 - The colors ouput should not include the `hsl` notation. Eg. `--secondary-20: 205deg 50% 20%;`
 
### Multiple values

We must be able to assign multiple values to the tokens. For example, inside CSS we'll use both `hsl` and `hex` formats.

## Do do

- [ ] Define raw scheme
- [ ] Setup generation tool
- [ ] Generate CSS and JSON tokens

**Comment by alessio-libardi** [comment]
For the tokens schema I would split them in two, for example:

**Primitives**
The primitives values such as colors, typography, spacing, etc
```json
{
  "color": {
    "blue": {
      "label": "The blue color",
      "value": "blue"
    }
  }
}
```

**Don't know how to name this category**
In this category we can place values that are not primitives and that instead refernce the primitives, all of this to separate values from meaning.
```json
{
  "color": {
    "primary": {
      "label": "The primary color of our brand",
      "value": "{color.blue}"
    }
  }
}
```
For the generation of the tokens I would use a lbrary such as [styled-dictionary](https://amzn.github.io/style-dictionary) that offers all the heavy lifting for the token generation and maintanance and would prefer not to use custom scripts to do it since they can easily become outdated, break and become a burden to maintain.

**Comment by equinusocio** [comment]
No color references must be placed inside tokens names. So we can't use this:

```
{
  "color": {
    "blue": {
      "label": "The blue color",
      "value": "blue"
    }
  }
}
```

Also you're already defining `"blue"` as label and then again a `"label": "blue"`. Also we don't need references inside tokens like "primary" etc, they are specific combinations of colors and they are handled by themes. I will update the issue with the requirements.

**Comment by alessio-libardi** [comment]
I understand what you mean, makes sense not to mix color references with design tokens!

For the scheme I wouldn't use different color format, I would leave up to the tool to transform a color to a specific format such as hex hsl etc, not to clutter the design tokens with formats, it's not up to the design token to specify the format but to the platform in which is used.

For the theming issue using style-dicitonary is just a matter of referencing variables as you could do in CSS or building two variable files depending on the theme, it's really up to us but it's not a difficult task once we decide how to approach it, then depending on the platform you decide to build them for color values or references (in css for example) are used.

**Comment by equinusocio** [comment]
> For the scheme I wouldn't use different color format, I would leave up to the tool to transform a color to a specific format such as hex hsl etc, not to clutter the design tokens with formats, it's not up to the design token to specify the format but to the platform in which is used.

We'll have to do a mass configuration/ custom transformers for the colors, because what I need inside the CSS is not a valid color format. For the CSS/JSON colors i need the output to be like this:

```css
:root {
 --primary-20: 230deg 50% 20%;
}
```

to being able to use it with the alpha channel without doing any extra step:

```css
div {
 color: hsl(var(--primary-20) 50%);
}
```

same for the JSON tokens:

```jsx
import tkns from '@wonderflow/tokens'

<div style={{color: `hsl(${tkns.primary} / 50%)`}}>
```
